server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

oauth:
  wx:
    appid: AppID
    appsecret: AppSecret

  callback:
    http: http://"IP:port"/wxcallback
