server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

oauth:
  wx:
    appid: wxd24fa8497766868c
    appsecret: 8df1088b9d7a3ef17c29a07d84a9fad5

  callback:
    http: http://192.168.0.111:8088/wxcallback
